# How to get the $\nabla^2$operator in tensorflow

In tensorflow, the default 2nd derivative operator will contract over the hessian matrix in an undesirable way.  For example:

In [1]:
import tensorflow  as tf
import tensorflow_probability as tfp

In [2]:
def generate_inputs(nwalkers, n_particles, dimension):
    x = tf.random.uniform(shape=[nwalkers, n_particles, dimension])
    return x

This function generates walkers in the same format as metropolis walkers, with random values

In [3]:
inputs = generate_inputs(4,1,2)

The function below creates a scalar value: f(x, y) = $\alpha x^2 + \beta y^2 + \gamma x y$

In [4]:
def wavefunction(inputs, alpha=0.1, beta=0.2, gamma=0.5):
    # return x^2 + y^2 + xy, with constants:
    ret = alpha * inputs[:,:,0]**2
    ret += beta * inputs[:,:,1]**2
    ret += gamma * inputs[:,:,0]*inputs[:,:,1]
    
    return tf.squeeze(ret)


In [5]:
output = wavefunction(inputs)

In [6]:
output.shape

TensorShape([4])

Here is the forward pass, telling tensorflow to watch the inputs since that's what we want to differentiate with respect to:

In [7]:
inputs = generate_inputs(4,1,2)

with tf.GradientTape(persistent=True) as outer_tape:
    outer_tape.watch(inputs)
    with tf.GradientTape(persistent=True) as inner_tape:
        inner_tape.watch(inputs)
        outputs = wavefunction(inputs)
    # Compute the first derivative with respect to the inputs
    dw_dx = inner_tape.gradient(outputs, inputs)

Note that we have to compute the first derivative, above, within the block of the outer_tape to compute a second derivative

This should have the same shape as the inputs, and the values are analytically computable (and thus checkable):

In [8]:
assert dw_dx.shape == inputs.shape

In [9]:
def analytic_derivative(inputs, alpha=0.1, beta=0.2, gamma=0.5):
    _x = inputs[:,:,0]
    _y = inputs[:,:,1]
    
    x = 2*alpha*_x + gamma*_y
    y = 2*beta*_y  + gamma*_x
    
    return tf.stack([x,y], axis=2)
    

In [10]:
dw_dx - analytic_derivative(inputs)

<tf.Tensor: shape=(4, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]], dtype=float32)>

The challenge, then, is the 2nd derivative.  We know what it *should* be if we're computing $\nabla^2$, but this is not what tensorflow computes:

In [11]:
def nabla_squared(inputs, alpha=0.1, beta=0.2, gamma=0.5):
    _x = tf.constant(2 * alpha, shape=inputs[:,:,0].shape)
    _y = tf.constant(2*beta, shape=inputs[:,:,1].shape)
    
    return tf.stack([_x, _y], axis=2)

In [12]:
nabla_squared(inputs)

<tf.Tensor: shape=(4, 1, 2), dtype=float32, numpy=
array([[[0.2, 0.4]],

       [[0.2, 0.4]],

       [[0.2, 0.4]],

       [[0.2, 0.4]]], dtype=float32)>

In [13]:
d2w_dx2 = outer_tape.gradient(dw_dx, inputs)

In [14]:
print(d2w_dx2)

tf.Tensor(
[[[0.7 0.9]]

 [[0.7 0.9]]

 [[0.7 0.9]]

 [[0.7 0.9]]], shape=(4, 1, 2), dtype=float32)


If you look closely, each value here is off by $\gamma$ - tensorflow is contracting the hessian to compute this second derivative!

In [15]:
d2wdx2 = outer_tape.jacobian(dw_dx, inputs)
print(d2wdx2)

tf.Tensor(
[[[[[[0.2 0.5]]

    [[0.  0. ]]

    [[0.  0. ]]

    [[0.  0. ]]]


   [[[0.5 0.4]]

    [[0.  0. ]]

    [[0.  0. ]]

    [[0.  0. ]]]]]




 [[[[[0.  0. ]]

    [[0.2 0.5]]

    [[0.  0. ]]

    [[0.  0. ]]]


   [[[0.  0. ]]

    [[0.5 0.4]]

    [[0.  0. ]]

    [[0.  0. ]]]]]




 [[[[[0.  0. ]]

    [[0.  0. ]]

    [[0.2 0.5]]

    [[0.  0. ]]]


   [[[0.  0. ]]

    [[0.  0. ]]

    [[0.5 0.4]]

    [[0.  0. ]]]]]




 [[[[[0.  0. ]]

    [[0.  0. ]]

    [[0.  0. ]]

    [[0.2 0.5]]]


   [[[0.  0. ]]

    [[0.  0. ]]

    [[0.  0. ]]

    [[0.5 0.4]]]]]], shape=(4, 1, 2, 4, 1, 2), dtype=float32)


The jacobian comes out with a dimension that is much too big.  We can contract it with "einsum":

In [16]:
tf.einsum("wpdwpd->wpd",d2wdx2)

<tf.Tensor: shape=(4, 1, 2), dtype=float32, numpy=
array([[[0.2, 0.4]],

       [[0.2, 0.4]],

       [[0.2, 0.4]],

       [[0.2, 0.4]]], dtype=float32)>

And now, that is the correct value for $\nabla^2$ of this function!

This is an equivalent implementation in our case where the output (per "batch") depends only on that input "batch":

In [23]:
tf.einsum("wpdpd->wpd",outer_tape.batch_jacobian(dw_dx, inputs))

<tf.Tensor: shape=(4, 1, 2), dtype=float32, numpy=
array([[[0.2, 0.4]],

       [[0.2, 0.4]],

       [[0.2, 0.4]],

       [[0.2, 0.4]]], dtype=float32)>